version: '3.8'

services:
  nginx:
    container_name: nginx
    build:
      #путь к каталогу с Dockerfile для nginx
      context: ./docker/nginx
    #проброс портов: порт котейнера (справа) пробрасывается на порт хост-машины
    ports:
      - ${NGINX_HOST_HTTP_PORT}:80
    volumes:
      #cоответствие даных в корневой директории проекта данным в /var/www контейнера
      - ./:/var/www
    #зависимость: контейнер nginx не запустится, если не запустится контенер php
    depends_on:
      - php
      - db

  php:
    container_name: php
    build:
      #путь к каталогу с Dockerfile для php
      context: ./docker/php
    volumes:
      #cоответствие даных в корневой директории проекта данным в /var/www контейнера
      - ./:/var/www

  db:
    container_name: db
    image: mysql:8.0.33
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3337:3306
    volumes:
     - ./docker/volume/mysql:/var/lib/mysql

